### ISSUE TITLE
Icon improvment for Plex Media Manager

### ISSUE THREAD

**Issue by leoheck** [numixproject/circle-core#2458]
Is it possible to improve the Plex Media *Manager* icon?

Currently we have:
![pelx](https://cloud.githubusercontent.com/assets/1277920/9149403/a893c2f4-3d7e-11e5-96cd-4ace3c6ed140.png)

The Plex Home Theater is awesome but the Media Manager is strange. 
For some ideas, the original: 

![pmm](https://cloud.githubusercontent.com/assets/1277920/9149406/c6e1501e-3d7e-11e5-9f61-fda24a2951c6.png)

Maybe using the original "donw arrow" with inverted colors from the Numix Plex Home Theater? What you thing?

**Comment by palob** [comment]
Well, the original icon isn't any less nondescript.

**Comment by leoheck** [comment]
Yes. But the current is very similar to xournal. In this way, it could be more similar to the Plex Home Theater, 
![xournal](https://cloud.githubusercontent.com/assets/1277920/9151442/dc0ce318-3dd8-11e5-985c-3cba4e3b02c6.png)

**Comment by Foggalong** [comment]
For reference [this is the original issue](https://github.com/numixproject/numix-icon-theme-circle/issues/404). The X is based on the Plex logo rather than the original icon. I can definitely see what you mean about the similarity to xjournal though.

Maybe copy the normal plex icon but rotate so the arrow is pointing downward and switch the gradient from blue to black.

**Comment by leoheck** [comment]
It will be a good solution.

**Comment by leoheck** [comment]
Thi isn't fixed! The improvement was not made.

**Comment by palob** [comment]
https://github.com/numixproject/numix-icon-theme-circle still needs to be regenerated.
